# Generated by Django 5.1.4 on 2025-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='job',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
