version: "3.0"
services:
  django:
    build: .
    container_name: django
    working_dir: /home/django_app
    ports:
      - "37564:8000"
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    # tty: true # 一時的な処置,runserverに置き換え予定
    volumes:
      - ./django_app:/home/django_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
