events {
    worker_connections  16;
}

http {
	server {
		listen 80;
		server_name  localhost;

		location /api/ {
			# djangoにリダイレクト
			proxy_pass http://host.docker.internal:37564/;
			proxy_set_header Host $host;
			proxy_redirect off;
		}

		# location /admin/{
		# 	# proxy_pass http://host.docker.internal:37564/admin/;
		# 	# proxy_set_header X-Forwarded-Host $host; 
		# 	# proxy_redirect off;
		# 	root /api
		# }
	}
}
