events {
    worker_connections  16;
}

http {
	server {
		listen 80;
		server_name  localhost;

		include mime.types;
		default_type application/octet-stream;


		location /api/ {
			# djangoにリダイレクト
			proxy_pass http://host.docker.internal:37564/;
			proxy_set_header Host $host;
			proxy_redirect off;
		}

		location /static/ {
			# djangoのstatic
			root /usr/share/nginx;
		}

		# location /admin/{
		# 	# proxy_pass http://host.docker.internal:37564/admin/;
		# 	# proxy_set_header X-Forwarded-Host $host; 
		# 	# proxy_redirect off;
		# 	root /api
		# }

	}
}
